HIMALAYAS_API_RESPONSE = {
    "comments": "13/03/2026: The API has been updated.",
    "updatedAt": 1774692720,
    "offset": 0,
    "limit": 20,
    "totalCount": 2,
    "jobs": [
        {
            "title": "AI Operations Manager",
            "excerpt": "Lead AI operations for a fast-growing startup...",
            "companyName": "Acme AI",
            "companySlug": "acme-ai",
            "companyLogo": "https://cdn-images.himalayas.app/logo123",
            "employmentType": "Full Time",
            "minSalary": 150000,
            "maxSalary": 200000,
            "seniority": ["Senior"],
            "currency": "USD",
            "locationRestrictions": ["United States", "Canada"],
            "timezoneRestrictions": [-8, -7, -6, -5],
            "categories": ["Operations-Manager", "AI-Operations"],
            "parentCategories": ["Operations"],
            "description": "<p>Lead AI operations...</p>",
            "pubDate": 1774692720,
            "expiryDate": 1779876720,
            "applicationLink": "https://himalayas.app/companies/acme-ai/jobs/ai-operations-manager",
            "guid": "https://himalayas.app/companies/acme-ai/jobs/ai-operations-manager",
        },
        {
            "title": "DevRel Engineer",
            "excerpt": "Build developer community...",
            "companyName": "ToolCo",
            "companySlug": "toolco",
            "companyLogo": "https://cdn-images.himalayas.app/logo456",
            "employmentType": "Full Time",
            "minSalary": None,
            "maxSalary": None,
            "seniority": ["Mid-level"],
            "currency": "USD",
            "locationRestrictions": [],
            "timezoneRestrictions": [],
            "categories": ["Developer-Relations"],
            "parentCategories": [],
            "description": "<p>Build developer community...</p>",
            "pubDate": 1774692665,
            "expiryDate": 1779876664,
            "applicationLink": "https://himalayas.app/companies/toolco/jobs/devrel-engineer",
            "guid": "https://himalayas.app/companies/toolco/jobs/devrel-engineer",
        },
    ],
}

EIGHTY_THOUSAND_HOURS_API_RESPONSE = {
    "nbHits": 2,
    "page": 0,
    "nbPages": 1,
    "hitsPerPage": 100,
    "hits": [
        {
            "objectID": "19948",
            "post_pk": 19948,
            "title": "Software Engineer, Core Technology",
            "company_name": "UK Government, AI Security Institute",
            "company": {"name": "UK Government, AI Security Institute"},
            "url_external": "https://job-boards.eu.greenhouse.io/aisi/jobs/4386112101?utm_source=80000hours",
            "description_short": "<ul>\n<li>Build evaluation frameworks.</li>\n</ul>",
            "tags_location_type": [],
            "tags_location_80k": ["London, UK", "UK"],
            "card_locations": ["London, UK"],
            "tags_city": ["London, UK"],
            "tags_country": ["UK"],
            "posted_at": 1781481900,
        },
        {
            "objectID": "19949",
            "post_pk": 19949,
            "title": "Finance Associate / Staff Accountant",
            "company_name": "Rethink Priorities",
            "company": {"name": "Rethink Priorities"},
            "url_external": "https://careers.rethinkpriorities.org/en/postings/9cd02f35",
            "description_short": "<p>Own the books.</p>",
            "tags_location_type": ["Remote"],
            "tags_location_80k": ["Remote, Global", "Global"],
            "card_locations": ["Remote, Global"],
            "tags_city": ["Remote, Global"],
            "tags_country": ["Remote, Global"],
            "posted_at": 1781481660,
        },
    ],
}
